### ISSUE TITLE
Automated test thinks that python3 package is pulling in python2

### ISSUE THREAD

**Issue by abadger** [fedora-python/task-python-versions#2]
https://taskotron.fedoraproject.org/artifacts/all/ad2d9846-de16-11e6-a19d-5254008e42f6/task_output/output.log

Here's the requires for the package:
```
[pts/27@roan /var/tmp]$ rpm -qp --requires python3-sphinx-1.4.8-3.fc24.noarch.rpm                         (23:41:30)
/bin/sh
/usr/bin/python3
/usr/sbin/alternatives
python(abi) = 3.5
python-sphinx-locale = 1.4.8-3.fc24
python3-babel
python3-docutils
python3-imagesize
python3-jinja2
python3-mock
python3-pygments
python3-six
python3-snowballstemmer
python3-sphinx-theme-alabaster
python3-sphinx_rtd_theme
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

My guess is that the python-sphinx-locale requirement is triggering the test.  However, that subpackage contains only locale data files with no dependency on python:
```
$ rpm -qp --requires python-sphinx-locale-1.4.8-3.fc24.noarch.rpm                   (23:47:10)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```
If that is in fact the problem, perhaps it is necessary to test if a python-* package requires python(abi) = 2.x before deciding whether it introduces a dependency on python2?

**Comment by hroncok** [comment]
The amount of packages that are called `python-*` but do not bring in Python 2 is very limited, so there's a white-list included in the code.

**Comment by hroncok** [comment]
@kparal Do i need to do anything to "deploy" the commit?

**Comment by mkrizek** [comment]
@hroncok Nope, it will happen automatically.

**Comment by kparal** [comment]
@hroncok It's going to be live in an hour or so. I recommend first pushing to `develop` branch so that you can verify that your task does not blow up spectacularly in dev environment (you can watch whether new results appear in http://taskotron-dev.fedoraproject.org/resultsdb/results?&testcases=dist.python-versions or alternatively you can watch whether it does not crash in https://taskotron-dev.fedoraproject.org/execdb/ ), and when it looks fine, push to `master` (which goes to production).

**Comment by hroncok** [comment]
Will do that next time.
